---
title: "Problem Set 2"
author: "Sneha Nimmagadda"
date: "16 September 2018"
output: word_document
---
1. Estimating Parameters of distributions.

```{r}

#Creating a function with N as argument and computing the mean and standard deviation and returning this in a vector.

myfunc <- function(n)
{
  myfunc <-c(mean(n),sd(n))
} 

####################################

m1<-matrix(nrow=500,ncol=2)#Making a matrix or data frame for each experiment representing 10 samples.

m2<-matrix(nrow=500,ncol=2)#Making a matrix or data frame for each experiment representing 100 samples.

m3<-matrix(nrow=500,ncol=2)#Making a matrix or data frame for each experiment representing 10000 samples.

#####################################

# 500 experiments for mean value of nnorm(10)
for(i in 1:500)
{
m1[i,]<-myfunc(rnorm(10))
}
#########

# 500 experiments for mean value of nnorm(100)

for(i in 1:500)
{
m2[i,]<-myfunc(rnorm(100))
}
#########

# 500 experiments for mean value of nnorm(10000)

for(i in 1:500)
{
m3[i,]<-myfunc(rnorm(10000))
}

#########
min(min(m1[,1]),min(m2[,1]),min(m3[,1]))
max(max(m1[,1]),max(m2[,1]),max(m3[,1]))
min(min(m1[,2]),min(m2[,2]),min(m3[,2]))
max(max(m1[,2]),max(m2[,2]),max(m3[,2]))

# Plotting Hist for all the samples in the same scale. 

hist(m1[,1],breaks=100,xlim=c(-2,2)); 
hist(m1[,2],breaks=100,xlim=c(-2,2));
hist(m2[,1],breaks=100,xlim=c(-2,2));
hist(m2[,2],breaks=100,xlim=c(-2,2));
hist(m3[,1],breaks=100,xlim=c(-2,2));
hist(m3[,2],breaks=100,xlim=c(-2,2));


```


2. Reading Data
```{r}
library(readxl) #Using inbuilt function to read Excel. 
Q2 <- read_excel("Q2.xlsx") #Reading file Q2 and assigning it to Q2. 

library(readxl) #Using inbuilt function to read Excel. 
Q2 <- read_excel("Q2.xlsx") #Reading file Q2 and assigning it to Q2. 
with(Q2,plot(Y1, xlab='Republicans',xpd= TRUE,Y2,ylab = "Democrats")) # Plotting Scattered plot as Republicans v/s Democrats. 
 with(Q2,abline(lsfit(Y1,Y2),col="red"))
 with(Q2,abline(line(Y1,Y2), col="blue"))
 mtext(side=3, line=0.5, "Republicans v/s Democrats", col="forestgreen", font=3, cex=2)
 with(Q2,text(Y1,Y2,labels = States))


 
# Plotting States v/s No. of Delegates 
 
with(Q2,plot(1:56, xaxt = "n", xlab='States',xpd= TRUE, ylab = "No. of Delegates",Y1, col="red", pch = 17))
with(Q2,points(1:56, xaxt = "n", xlab='States', xpd= TRUE,ylab = "No. of Delegates",Y2, col="blue", pch = 17))
mtext(side=3, line=0.5, "States v/s No. of Delegates", col="forestgreen", font=3, cex=2)

labels=c('Alabama','Alaska','Amer. Samoa','Arizona','Arkansas','California','Colorado','Connecticut','Delaware','DC','Florida','Georgia','Guam','Hawaii','Idaho','Illinois','Indiana','Iowa','Kansas','Kentucky','Louisiana','Maine','Maryland','Massachusetts','Michigan','Minnesota','Mississippi','Missouri','Montana','Nebraska','Nevada','New Hampshire','New Jersey','New Mexico','New York','North Carolina','North Dakota', 'N. Marianas', 'Ohio','Oklahoma','Oregon','Pennsylvania','Puerto Rico','Rhode Island','South Carolina','South Dakota','Tennessee','Texas','Utah','Vermont','Virgin Islands','Virginia','Washington','West Virginia','Wisconsin','Wyoming')
abline(h=seq(0,700,20), v=seq(0,80, 1), lty=3, col="gray")
axis(1, at=1:56, labels=c('Alabama','Alaska','Amer. Samoa','Arizona','Arkansas','California','Colorado','Connecticut','Delaware','DC','Florida','Georgia','Guam','Hawaii','Idaho','Illinois','Indiana','Iowa','Kansas','Kentucky','Louisiana','Maine','Maryland','Massachusetts','Michigan','Minnesota','Mississippi','Missouri','Montana','Nebraska','Nevada','New Hampshire','New Jersey','New Mexico','New York','North Carolina','North Dakota', 'N. Marianas', 'Ohio','Oklahoma','Oregon','Pennsylvania','Puerto Rico','Rhode Island','South Carolina','South Dakota','Tennessee','Texas','Utah','Vermont','Virgin Islands','Virginia','Washington','West Virginia','Wisconsin','Wyoming'))

      

```
3. Filtering and Sorting
```{r}

#Reading the data into R
senate.2014 <- read.csv("D:/MTU MS/SEM 1/ASAD/Problem Set 2/senate-2014.csv") 

#Using the summary function
   summary(senate.2014) 
   
#Using the table function
   table(senate.2014$Affiliation)
   table(senate.2014$FirstName)
   table(senate.2014$LastName)
   table(senate.2014$AssumedOffice)
   table(senate.2014$DOB)
   table(senate.2014$Gender)
   table(senate.2014$Age)
   table(senate.2014$YearsServed)
   table(senate.2014$Affiliation,senate.2014$Gender)
   
 #Using the boxplot function
  
   boxplot(senate.2014)
   
  #Using the hist function

   hist(senate.2014$Age)
   hist(senate.2014$YearsServed)
   hist(senate.2014$AssumedOffice)

  # Those who have served more than 10 years:
   
   
  # Using aggregate to compute the mean age of senators by party and gender: 
   
  
   print(aggregate (senate.2014$Age, list(PartyName=senate.2014$Affiliation), mean ))
   
   # Using aggregate to compute the mean age of senators by party and gender: 
   
  
   print(aggregate (senate.2014$Age, list(Gender=senate.2014$Gender), mean ))
   
   #Sorting the data by seniority (years served)
   SORTEDYEARS<-sort(senate.2014$YearsServed)
   #Sorting the data by Age 
   SORTEDAGE<-sort(senate.2014$Age)
  
   matplot(SORTEDYEARS,SORTEDAGE)
   
   
   

       
```


4. Programming in R
```{r}
#Create a function DoLetters that takes a single integer argument, and returns the alphabet up to that number:

DoLetters<- function(n)
{
  DoLetters<- LETTERS[1:n]
}

print(DoLetters(5))

#Create a function that takes two arguments that are integers between 1 and 26, and returns the sublist indicated by that range

DoLetters2 <-function(x,y)
{
    DoLetters2<- LETTERS[x:y]

}




```


